style(home): Add hover effect on card
pancakeswap/pancake-frontend pull request #1026
Opened 2021-04-29 00:00 UTC by noblica

Wrapped entire blocks into the `<NavLink>` component, so it's entirely clickable.
Also added a hover effect, to make it clearer that the element is clickable.

Here's how it looks now:

https://user-images.githubusercontent.com/9339019/116486644-61872000-a88e-11eb-9b28-f053f0023ae5.mp4

Please let me know if the hover effect is fine, or if further changes are needed :slightly_smiling_face:

2021-04-29 03:33 UTC, ChefBugs commented
Thanks! The hover effect is a bit aggressive though, for now please let's use the same hover effect as the buttons https://pancakeswap.github.io/pancake-uikit/?path=/story/components-button--default

2021-04-29 09:07 UTC, noblica commented
Hey @ChefBugs , thanks for the feedback.
I updated the PR so now the hover effect looks like this:

https://user-images.githubusercontent.com/9339019/116527577-1c3d0f80-a8db-11eb-933a-3300261573cf.mp4


Please let me know if more changes are needed :slightly_smiling_face:

2021-04-29 09:24 UTC, hachiojidev requested changes

2021-04-29 09:24 UTC, hachiojidev commented on src/views/Home/components/EarnAPRCard.tsx
> +    transition: opacity 200ms;
No need to add the `transition` property on this line.

2021-04-29 09:24 UTC, hachiojidev commented on src/views/Home/components/EarnAssetCard.tsx
> +    transition: opacity 200ms;
Same here

2021-04-29 09:24 UTC, hachiojidev commented on src/views/Home/components/WinCard.tsx
> +    transition: opacity 200ms;
And here...

2021-05-05 23:31 UTC, hachiojidev commented
@noblica Please resolve conflicts

2021-05-05 23:49 UTC, noblica commented
@hachiojidev Done :+1:

2021-05-06 05:35 UTC, hachiojidev approved these changes

2021-05-06 05:35 UTC, merged