feat (prediction) use user language for tradingview
pancakeswap/pancake-frontend pull request #1228
Opened 2021-05-17 13:56 UTC by ciruz

Noticed the language in the TradingView is hardcoded so I extended it, now the language from the user settings getting used in the TradingView.

![image](https://user-images.githubusercontent.com/987947/118499279-104cac80-b727-11eb-821f-6017ea5dac6e.png)

![image](https://user-images.githubusercontent.com/987947/118499303-15a9f700-b727-11eb-8cbe-6799e757428e.png)

If the language isn't available, the TradingView widget will be english by default (so no issues with incompatible codes).

Some language codes from PCS are not compatible with the TradingView widget, since their language codes are also a little inconsistent at some point (german is "de_DE", spanish is "es").

![image](https://user-images.githubusercontent.com/987947/118499635-6ae60880-b727-11eb-990f-3ec6681642ad.png)

I'm not sure about this one, maybe one day someone extend the language interface ex. for a tradingview language, to be fully compatible:

![image](https://user-images.githubusercontent.com/987947/118500597-3888db00-b728-11eb-9895-2309f1bbb0cc.png)

2021-05-17 22:55 UTC, hachiojidev requested changes
Nice work, just one thing to adjust.

2021-05-17 22:55 UTC, hachiojidev commented on src/views/Predictions/components/TradingView.tsx
> +  const { currentLanguage } = useContext(LanguageContext);
`const { currentLanguage } = useTranslation()`

2021-05-18 01:52 UTC, Chef-Chungus commented
@ciruz - Please run prettier on this one too

2021-05-18 06:46 UTC, ciruz commented on src/views/Predictions/components/TradingView.tsx
> +  const { currentLanguage } = useContext(LanguageContext);
thanks

2021-05-18 06:46 UTC, ciruz commented
done @Chef-Chungus

2021-05-19 00:42 UTC, hachiojidev approved these changes

2021-05-19 00:42 UTC, merged