fix: Add missing translations in team battle
pancakeswap/pancake-frontend pull request #1352
Opened 2021-05-26 10:15 UTC by memoyil

2021-05-26 23:39 UTC, hachiojidev requested changes

2021-05-26 23:39 UTC, hachiojidev commented on src/views/TradingCompetition/index.tsx
> +import { useTranslation } from '../../contexts/Localization'
Absolute import please.

2021-05-26 23:41 UTC, memoyil commented on src/views/TradingCompetition/index.tsx
> +import { useTranslation } from '../../contexts/Localization'
done

2021-05-27 05:52 UTC, hachiojidev approved these changes

2021-05-27 05:52 UTC, merged