chore(lottery-v1): Remove all lottery v1 code from codebase
pancakeswap/pancake-frontend pull request #1649
Opened 2021-07-06 07:43 UTC by ChefHutch

2021-07-06 11:05 UTC, ChefHutch commented on src/views/Lottery/components/Hero.tsx
> +import styled, { keyframes } from 'styled-components'
This is a straight delete of v1 and replace with v2, but the file name is the same, so Git is parsing it as a diff

`views/Lottery/components/Hero` > deleted
`views/LotteryV2/components/Hero` >  renamed `views/Lottery/components/Hero`

2021-07-06 12:33 UTC, Chef-Cheems requested changes
Messaged in slack about additional removals

2021-07-06 12:55 UTC, Chef-Cheems approved these changes

2021-07-07 01:32 UTC, RabbitDoge commented on package.json
> -    "react-chartjs-2": "2.11.1",
and `chart.js` ?

2021-07-07 07:43 UTC, ChefHutch commented on package.json
> -    "react-chartjs-2": "2.11.1",
Good point, removed

2021-07-07 08:08 UTC, RabbitDoge approved these changes

2021-07-07 08:12 UTC, merged