Axs - 18:00
pancakeswap/pancake-frontend pull request #1744
Opened 2021-07-16 16:02 UTC by Chef-Chungus

poooll
--------------
**Stake:** AXS
**Stake Token Contract Address:** 0x715D400F88C167884bbCc41C5FeA407ed4D2f8A0
**Earn:** CAKE
**Earn Token Contract Address:** 0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
**Rewards per block:** 0.03968
**Max Stake per wallet:** 20 AXS
**Start block:** 9231500
**End block:** 9433100
** AXS Token Decimals:** 18
**Axie Infinity Project website:** https://axieinfinity.com/

farm
-------------- 
**Stake LP Token:** AXS-BNB LP Token
**LP Token Contract Address:** https://bscscan.com/address/0xc2d00de94795e60fb76bc37d899170996cbda436
**Earn:** CAKE
**Multiplier:** 2x for the first 48 hours, then 1x

2021-07-16 16:22 UTC, ChefKai requested changes

2021-07-16 16:22 UTC, ChefKai commented on src/config/constants/farms.ts
> +      56: '',
Missing LP address

2021-07-16 16:37 UTC, ChefKai commented on src/config/constants/farms.ts
> +      56: '',
Fixed with ab201d67a7b5b2b1f460cdd10148a71ec11ae317

2021-07-16 16:38 UTC, ChefKai approved these changes

2021-07-17 05:11 UTC, merged

2021-07-17 05:30 UTC, aldoromo88 commented
Hello team, do u realized that voting ended with 77% votes for No?
are u still deploying this one?

cc: @Chef-Chungus