fix(voting): Page overflow fixed
pancakeswap/pancake-frontend pull request #2789
Opened 2021-11-29 02:47 UTC by onlychild

reactmarkdown adopt to <a> Tag

2021-11-29 05:34 UTC, chef-jojo commented
Thanks @onlychild 
I also noticed that Table is causing overflow as well
https://pancakeswap.finance/voting/proposal/Qme3CW5NBYEeECXbFwnNRZME44oBwMRy93fQeRdz7to6qn
Could you help it? I think It'd be great if the table itself can be scrolled

2021-11-29 06:12 UTC, onlychild commented
> Thanks @onlychild I also noticed that Table is causing overflow as well https://pancakeswap.finance/voting/proposal/Qme3CW5NBYEeECXbFwnNRZME44oBwMRy93fQeRdz7to6qn Could you help it? I think It'd be great if the table itself can be scrolled

fixed!! by the way，can you granted the develop permission of https://github.com/pancakeswap/pancake-uikit? the ux of the bottomNav Component maybe has some bugs！

2021-11-29 07:00 UTC, chef-jojo commented
> > Thanks @onlychild I also noticed that Table is causing overflow as well https://pancakeswap.finance/voting/proposal/Qme3CW5NBYEeECXbFwnNRZME44oBwMRy93fQeRdz7to6qn Could you help it? I think It'd be great if the table itself can be scrolled
> 
> 
> 
> fixed!! by the way，can you granted the develop permission of https://github.com/pancakeswap/pancake-uikit? the ux of the bottomNav Component maybe has some bugs！

Moved here https://github.com/pancakeswap/pancake-toolkit

2021-11-29 07:28 UTC, chef-jojo requested changes

2021-11-29 08:24 UTC, onlychild commented on src/components/ReactMarkdown/styles.tsx
> +const Box = styled.div`
TableBox

2021-12-01 02:33 UTC, chef-jojo commented on src/components/ReactMarkdown/styles.tsx
> +  // table: Table,
please remove this line

2021-12-01 08:59 UTC, onlychild commented on src/components/ReactMarkdown/styles.tsx
> +  // table: Table,
done

2021-12-01 10:48 UTC, chef-jojo approved these changes

2021-12-04 18:42 UTC, Chef-Cheems approved these changes

2021-12-04 18:56 UTC, merged