perf: Route-based code splitting
pancakeswap/pancake-frontend pull request #301
Opened 2021-01-15 06:28 UTC by RabbitDoge

Split the JS bundle based on react-router routes

2021-01-15 06:36 UTC, RabbitDoge commented
Waiting for the designer input about the loading component

2021-01-18 08:50 UTC, hachiojidev requested changes
Just one issue I see is that the loader.

- It is too big and not responsive
- It should be centered vertically

2021-01-18 08:50 UTC, hachiojidev commented on src/App.tsx
> +const NotFound = lazy(() => import('./views/NotFound'))
Probably not needed for this but we should consider keeping critical routes in the bundle.

2021-01-19 09:55 UTC, hachiojidev approved these changes

2021-01-20 01:06 UTC, merged