Farm card updates
pancakeswap/pancake-frontend pull request #321
Opened 2021-01-18 20:06 UTC by RichardPK

**Notes**
- UI Kit PR needs merging & releasing before this can be finished https://github.com/pancakeswap/pancake-uikit/pull/124
- Once reviewed I'll delete the existing farm components.

The client side load is now fairly extreme in terms of smart contract calls. What was previously happening on an individual farm-by-farm basis when the farm page was visited, is now being done for _all_ farms. Should we implement some sort of lazyload for these components to help? What would be preferred? I'd propose trying:
- Lazyload (i.e. loaded as they are scrolled into viewport) the harvest & staking actions components + respective contract calls
- Only load total liquidity after ‘details’ button press
- Alternatively we could lazyload the entirety of every card, but the user might experience a fair bit of loading state as they scroll.

**Overview**
- Modifying the existing `FarmCard` component to encapsulate most of the changes in the new designs:

<img width="1007" alt="Screenshot 2021-01-10 at 16 45 28" src="https://user-images.githubusercontent.com/9042672/104129147-54880480-5363-11eb-9455-e0ed7d6ab9fe.png">

**For a later PR:**
- APY calculator
- Modal updates

**Code changes**

Farm Cards:
- A lot of the old `FarmCard` broken into separate components
- `HarvestAction` and `StakingAction` responsible for the staking/harvesting buttons & calculating relevant values
- `CardActionsContainer` is responsible for rendering the 'actions' section of the card - Staking, Harvesting and account-unlocking.
- `CardHeading` is a simple FE component rendering the top section of the card
- `DetailsSection` is a simple FE component responsible for rendering information that appears when the user clicks the 'details' button

Other:
- Made the Lottery `DetailsButton` more generic, to be used for any collapsable sections - `ExpandableSectionButton`. There are also some minor changes to `TotalPrizesCard` following this
- Created a util to get the first and second parts of an LP url - `getLiquidityUrlPathParts`

2021-01-18 20:59 UTC, RichardPK commented on src/views/Farms/Farms.tsx
> +    [bnbPrice, farmsLP, account, cakePrice, ethereum],
This function is pretty damn nasty to start with, I just added dependencies to the hook as they're required by the new farm cards

2021-01-19 08:10 UTC, RabbitDoge requested changes

2021-01-19 08:10 UTC, RabbitDoge commented on src/views/Farms/components/FarmCard/DetailsSection.tsx
> +        <StyledLink external href={`https://exchange.pancakeswap.finance/#/add/${liquidityUrlPathParts}`}>
You have a component doing this here https://github.com/pancakeswap/pancake-uikit/blob/master/src/components/Link/LinkExternal.tsx#L6

2021-01-19 08:10 UTC, RabbitDoge commented on src/views/Farms/components/FarmCard/DetailsSection.tsx
> +        <Link external href={bscScanAddress} target="_blank" bold={false}>
the `target="_blank"` is already applied by the `external` props

2021-01-19 08:10 UTC, RabbitDoge commented on src/views/Farms/components/FarmCard/FarmCard.tsx
> +const RainbowLight = keyframes`
not sure why prettier is not formatting this 🤔

2021-01-19 18:13 UTC, RichardPK commented on src/views/Farms/Farms.tsx
> +    [bnbPrice, farmsLP, account, cakePrice, ethereum],
👍

2021-01-19 18:24 UTC, RichardPK commented on src/utils/getLiquidityUrlPathParts.ts
> +const getLiquidityUrlPathParts = ({ quoteTokenAdresses, quoteTokenSymbol, tokenAddresses }) => {
Cool - have done. Frankly I'm not 100% why ETH is used here? But it is how the 'Add Liquidity' urls are constructed nonetheless, so I mirrored it. A hangover from the sushi fork?

2021-01-19 18:28 UTC, RichardPK commented on src/views/Farms/components/FarmCard/CardActionsContainer.tsx
> +      {/* TODO: These text elements should make use of updated textTransform prop when uikit version is deployed */}
Akh annoyingly I added a bug in the `textTransform` implementation - fixed here https://github.com/pancakeswap/pancake-uikit/pull/139 (I think it was actually included by travioli in another PR, so it's in and release. I'll remove the comment)

2021-01-19 18:31 UTC, RichardPK commented on src/views/Farms/components/FarmCard/CardActionsContainer.tsx
> +      {/* TODO: These text elements should make use of updated textTransform prop when uikit version is deployed */}
I've brought in uikit 0.9.0 which has the fix in it 👍

2021-01-20 00:52 UTC, hachiojidev approved these changes

2021-01-20 08:55 UTC, RabbitDoge commented on src/utils/getLiquidityUrlPathParts.ts
> +const getLiquidityUrlPathParts = ({ quoteTokenAdresses, quoteTokenSymbol, tokenAddresses }) => {
Yes probably from the Sushi fork

2021-01-22 07:02 UTC, RabbitDoge approved these changes

2021-01-22 07:02 UTC, merged