feat: Prediction
pancakeswap/pancake-frontend pull request #364
Opened 2021-01-31 15:25 UTC by pancake-cat

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

2021-02-01 01:07 UTC, hachiojidev requested changes
A few things I noticed.

2021-02-01 01:07 UTC, hachiojidev commented on src/views/Prediction/components/CountDown.tsx
> +  style?: Record<string, string>
This should be `React.CSSProperties`

2021-02-01 01:07 UTC, hachiojidev commented on src/views/Prediction/components/CountDown.tsx
> +}
Please use `getTimePeriods`

2021-02-01 01:07 UTC, hachiojidev commented on src/views/Prediction/components/CountDown.tsx
> +  const _seconds = seconds > 0 ? seconds : 0
Please remove the underscore.

2021-02-01 01:07 UTC, hachiojidev commented on src/views/Prediction/components/PredictionItem.tsx
> +`
Please use the UI Kit's `<Flex />` component

2021-02-01 01:07 UTC, hachiojidev commented on tsconfig.json
> +    "jsx": "react",
This is incorrect. Please update your IDE's typescript version and revert this.

2021-02-01 01:07 UTC, hachiojidev commented on src/views/Prediction/components/TradingView.tsx
> +`
Please use the Flex component

2021-02-01 01:07 UTC, hachiojidev commented on src/views/Prediction/components/PredictionList.tsx
> +          <PredictionItem {...item} />
This needs a key

2021-02-04 16:14 UTC, pancake-cat commented on src/hooks/useMarketTrade.ts
> +  }, [])
yes

2021-02-04 16:43 UTC, pancake-cat commented on src/hooks/useTimer.ts
> +  const [remine, setRemine] = useState(initSecond)
a typo issue, fixed, thank you

2021-02-24 00:59 UTC, closed without merging