feat: Filtering farming pools & farms
pancakeswap/pancake-frontend pull request #416
Opened 2021-02-08 13:05 UTC by heyimbrucelee

Filtering farming pools & farms
New filter button 'farming' between active & inactive

2021-02-09 00:22 UTC, hachiojidev requested changes
Thanks! Just a few things to update

- Left one comment
- Linting errors

2021-02-09 00:22 UTC, hachiojidev commented on src/views/Farms/Farms.tsx
> +    .filter((farm) => farm.userData && farm.userData.stakedBalance > new BigNumber(0))
No need to for two filters, we can use `activeFarms`

```
const farmingFarms = activeFarms.filter...
```

2021-02-09 02:42 UTC, Chef-Chungus commented
@heyimbrucelee Thanks for taking the time to submit this. We'll award you with a bounty in CAKE after the merge and deployment of this. 

Just some feedback from our designer @ChefBugs

Can you please add this as a toggle switch instead of a tab, for styling information please check our [Figma](https://www.figma.com/file/q5dKq3BuQZ4YzV5pR0Mt2M/Design-System-UI?node-id=2060%3A9400)
![image](https://user-images.githubusercontent.com/71833681/107308316-c4f18500-6acb-11eb-9fa8-0b384fe99929.png)

2021-02-09 12:32 UTC, Chef-Chungus commented
@heyimbrucelee come join our slack
Let’s chat about dev, compensation for this and other stuff 
https://join.slack.com/t/cakecommunitydev/shared_invite/zt-l01lbyk3-o47UMVjSps2NEfQivctCZg

2021-02-10 06:52 UTC, RabbitDoge requested changes
this pull request doesn't follow our coding styles.
Please read the contribution guidelines, and setup prettier.

2021-02-10 06:52 UTC, RabbitDoge commented on src/views/Farms/Farms.tsx
> +  const stackedOnlyFarms = activeFarms.filter((farm) => farm.userData && farm.userData.stakedBalance > new BigNumber(0))
please use https://mikemcl.github.io/bignumber.js/#gt

2021-02-10 06:52 UTC, RabbitDoge commented on src/views/Farms/Farms.tsx
> +  const [stackedOnly,setStackedOnly] = useState(0);
should be a bool, not a number

2021-02-10 06:52 UTC, RabbitDoge commented on src/views/Pools/Syrup.tsx
> +  const [stackedOnly,setStackedOnly] = useState(0);
same

2021-02-12 06:23 UTC, RabbitDoge approved these changes

2021-02-12 06:25 UTC, hachiojidev approved these changes

2021-02-12 06:36 UTC, merged