feat: bCake boostCard and migrationModal
pancakeswap/pancake-frontend pull request #4316
Opened 2022-07-23 01:40 UTC by Chef-Yogi

2022-07-23 03:50 UTC, chefilip commented on src/views/Farms/components/BCakeBoosterCard.tsx
> +        <ConnectWalletButton />
How about user hasn't licked cake yet? It should have a Go to pool button, right?

2022-07-25 02:50 UTC, chef-jojo requested changes

2022-07-25 02:50 UTC, chef-jojo commented on src/views/Farms/hooks/useUserBoosterStatus.ts
> +  const { data: MAX_BOOST_POOL, status: maxBoostStatus } = useSWR('maxBoostFarm', () =>
Can use swr immutable

2022-07-25 02:50 UTC, chef-jojo commented on src/views/Farms/hooks/useUserBoosterStatus.ts
> +  const { data: activatedPools, status } = useSWR(['activatedBoostFarm', account], () =>
acount && []

2022-07-25 02:50 UTC, chef-jojo commented on src/views/Farms/hooks/useBCakeProxyContractAddress.ts
> +  const { data, status } = useSWR(['proxyAddress', account], async () =>
acount && contract

2022-07-25 02:50 UTC, chef-jojo commented on src/views/Farms/components/BCakeMigrateModal.tsx
> +type Steps = 'unStake' | 'enable' | 'stake'
prefer enum here

2022-07-25 02:50 UTC, chef-jojo commented on src/views/Farms/components/BCakeMigrateModal.tsx
> +  unStake: 'Unstake LP tokens from the farm',
Pass transalte fn or use Trans

2022-07-25 02:53 UTC, chef-jojo commented on src/state/pools/hooks.ts
> +export const usePoolsUserData = () => {
rename it as useCakeVaultUserData

2022-07-25 02:54 UTC, chef-jojo commented on src/views/Farms/components/BCakeMigrateModal.tsx
> +  }, [lpContract, bCakeProxy])
can move this effect into useApproveBoostProxyFarm, and use swr instead of effect

2022-07-25 02:57 UTC, chef-jojo commented on src/views/Farms/components/BCakeMigrateModal.tsx
> +    <Modal title="Migrate your stakings" width="420px" onDismiss={onDismiss}>
translate

2022-07-25 02:58 UTC, chef-jojo commented on src/views/Farms/components/BCakeMigrateModal.tsx
> +  unStake: 'Unstake LP tokens from the farm',
and use enum as object key

2022-07-25 02:59 UTC, chef-jojo commented on src/views/Farms/components/BCakeBoosterCard.tsx
> +  useUserLockedCakeStatus()
remove this line

2022-07-25 03:00 UTC, chef-jojo commented on src/views/Farms/components/BCakeBoosterCard.tsx
> +              await farmBoosterProxyFactoryContract.createFarmBoosterProxy({ gasLimit: DEFAULT_GAS_LIMIT })
please use fetchWithCallError and refetch it after

2022-07-25 04:40 UTC, chef-jojo commented on src/views/Farms/hooks/useUserBoosterStatus.ts
> +  const { data: activatedPools, status } = useSWR(['activatedBoostFarm', account && []], () =>
```suggestion
  const { data: activatedPools, status } = useSWR(account && ['activatedBoostFarm', account], () =>
```

2022-07-25 04:43 UTC, chef-jojo commented on src/views/Farms/hooks/useBCakeProxyContractAddress.ts
> +  const { data, status } = useSWR(['proxyAddress', account && bCakeFarmBoosterContract], async () =>
```suggestion
  const { data, status } = useSWR(account && ['proxyAddress', bCakeFarmBoosterContract], async () =>
```

2022-07-28 06:52 UTC, closed without merging