Bounty: Easteregg
pancakeswap/pancake-frontend pull request #436
Opened 2021-02-12 04:21 UTC by luisantoniocrag

This PR adds an easteregg when konamiCode is typed: [up, up, down, down, left, right, left, right, b, a]

At Slack we agreed to call this effect `walletRouting`

This use: #[180](https://github.com/pancakeswap/pancake-uikit/pull/180) in uikit repository
Example: 
![easteregg](https://user-images.githubusercontent.com/42625753/107729735-49ecc200-6cb7-11eb-802f-1385ff2757f8.gif)

2021-02-12 04:23 UTC, karelianpie commented on src/components/Menu/index.tsx
> +      account={account}z
Accidental `z`

2021-02-12 05:37 UTC, RabbitDoge requested changes
See the slack dev group for the feedbacks

2021-02-16 05:47 UTC, hachiojidev commented
@luisantoniocrag Moving forward please follow our commit message guidelines.
https://docs.pancakeswap.finance/code/contributing#committing

2021-02-16 17:13 UTC, closed without merging

2021-02-20 06:30 UTC, Chef-Chungus commented
Feedback:

**What 100% need to be changed:**

- Follow the team’s coding rules (linting and prettify)
- Move the konami code hook inside the uikit and make it generic
- Remove the conditional hook call inside the Konami hook

**What may need to be changed:**

- The hack with setTimeout + setInterval is probably not needed
- Maybe using a component that will render the animation for X seconds will be cleaner than modify the dom directly. You can render/not render this component based on what happen in the konami code hook

**Suggestions**
The Konami hook should take a callback as a param, and call this function when the konami code is triggered
You can create a WalletRouting component that will replace the useWalletRouting hook. This component will ruse the konamiCode hook , and render or not the animation by using a state props, and pass the setState as the callback of the konamiCode hook

As a rule of thumb, it’s better to not mutate the dom directly when using React