Pan 587 red alarm implementing with mock api
pancakeswap/pancake-frontend pull request #4407
Opened 2022-08-04 11:26 UTC by ChefMomota

- [ ] Hide all when is native token
- [ ] Hide when chainId is not BSC

2022-08-04 11:47 UTC, ChefMomota commented on src/views/Swap/components/AccessRisk/index.tsx
> +    localStorage.setItem(TOKEN_RISK_KEY, JSON.stringify(newData))
Actually is not all risk token. Just can give user check that token is risk or not.
So we will save the data, User will not need to keep checking if the token is risky.

2022-08-05 03:38 UTC, ChefMomota commented on src/views/Swap/components/AccessRisk/index.tsx
> +    setIsAccessing(false)
nice catch

2022-08-15 02:20 UTC, chef-jojo commented on src/views/Swap/hooks/fetchTokenRisk.ts
> +  const listUrl = VerifyTokensLink[chainId]
can just use `combinedTokenMapFromOfficialsUrlsSelector`

2022-08-25 15:25 UTC, chef-jojo commented on src/views/Swap/index.tsx
> +    return isAccessTokenSupported && currencies[Field.OUTPUT]?.symbol !== 'BNB'
?.isNative

2022-08-25 16:24 UTC, ChefMomota commented on src/views/Swap/index.tsx
> +    return isAccessTokenSupported && currencies[Field.OUTPUT]?.symbol !== 'BNB'
yup. will update

2022-09-02 03:08 UTC, chef-jojo requested changes

2022-09-02 03:08 UTC, chef-jojo commented on .env.development
> +NEXT_PUBLIC_ACCESS_RISK = "https://red.alert.pancakeswap.com/red-api"
No need to set in env

2022-09-02 03:08 UTC, chef-jojo commented on src/views/Swap/index.tsx
> +    return isAccessTokenSupported && currencies[Field.OUTPUT]?.symbol !== NATIVE[chainId].symbol
IsNative

2022-09-02 03:20 UTC, ChefMomota commented on src/views/Swap/index.tsx
> +    return isAccessTokenSupported && currencies[Field.OUTPUT]?.symbol !== NATIVE[chainId].symbol
@chef-jojo  done

2022-09-02 03:20 UTC, ChefMomota commented on .env.development
> +NEXT_PUBLIC_ACCESS_RISK = "https://red.alert.pancakeswap.com/red-api"
done

2022-09-02 03:24 UTC, chefilip commented on src/views/Swap/components/AccessRisk/index.tsx
> +    const tokenRiskResult: RiskTokenInfo = await fetchRiskToken(address, chainId)
should we use `useSWR` to cache the resquest

2022-09-02 03:48 UTC, chefilip approved these changes

2022-09-02 05:32 UTC, chef-jojo approved these changes

2022-09-02 05:39 UTC, merged