feat: add price to document title
pancakeswap/pancake-frontend pull request #469
Opened 2021-02-16 10:18 UTC by Rovak

Adds the current CAKE price to the document title

![Screenshot from 2021-02-16 18-17-23](https://user-images.githubusercontent.com/376155/108049448-3e1c4980-7083-11eb-96ec-0207726fe123.png)

2021-02-17 00:05 UTC, hachiojidev requested changes
Thank you for submitting your PR. In this case I don't think bringing on an extra dependency to change the document title is necessary. If you look at the hook's source you'll see it is pretty simple.

https://github.com/streamich/react-use/blob/master/src/useTitle.ts

2021-02-17 00:05 UTC, hachiojidev commented on src/DocumentTitle.tsx
> +const DocumentTitle = ({ title, showPrice = true }) => {
Missing types

2021-02-17 00:05 UTC, hachiojidev commented on src/DocumentTitle.tsx
> +  // Append price if enabled
Try and use comments only if the code needs supplemental explanation. I think this case it is pretty obvious what is happening.

2021-02-17 00:05 UTC, hachiojidev commented on src/DocumentTitle.tsx
> +  // Append title
Same here

2021-02-24 00:48 UTC, Chef-Chungus commented
Closed in favor of #494

2021-02-24 00:48 UTC, closed without merging