refactor(mono): Prepare patch 3
pancakeswap/pancake-frontend pull request #4942
Opened 2022-10-11 19:38 UTC by chefilip

2022-10-12 01:57 UTC, chef-jojo requested changes

2022-10-12 01:57 UTC, chef-jojo commented on packages/wagmi/package.json
> -  "main": "./dist/index.js",
It's a published package

2022-10-15 19:36 UTC, chefilip commented on packages/wagmi/package.json
> -  "main": "./dist/index.js",
Oh. I see. Revert it.

2022-10-17 02:08 UTC, chef-jojo commented on packages/wagmi/package.json
> -  "main": "./dist/index.js",
revert all in this file?

2022-10-17 13:42 UTC, chefilip commented on packages/wagmi/package.json
> -  "main": "./dist/index.js",
Done

2022-10-25 13:46 UTC, chef-jojo approved these changes

2022-10-25 14:56 UTC, merged