Bounty: easter-egg feature
pancakeswap/pancake-frontend pull request #514
Opened 2021-02-24 01:16 UTC by z3s

Add EasterEgg feature (falling bunnies).
use components from this PR https://github.com/pancakeswap/pancake-uikit/pull/192

2021-02-24 02:57 UTC, RabbitDoge requested changes

2021-02-24 02:57 UTC, RabbitDoge commented on src/components/EasterEgg/EasterEgg.tsx
> +export interface EasterEggProps {
Use the exported type from the uikit

2021-02-25 01:35 UTC, hachiojidev commented
Same as the UI Kit PR, the commit messages need to be fixed.
https://docs.pancakeswap.finance/code/contributing#committing

2021-02-26 00:11 UTC, hachiojidev approved these changes

2021-02-26 06:27 UTC, RabbitDoge requested changes
Need to update the uikit to this version https://github.com/pancakeswap/pancake-uikit/releases/tag/v0.11.2 in order to have the easter eggs components

2021-02-26 08:41 UTC, RabbitDoge approved these changes

2021-02-26 08:42 UTC, merged