chore(Info): Info pools redirection
pancakeswap/pancake-frontend pull request #5287
Opened 2022-11-13 05:26 UTC by Woody810

2022-11-13 05:31 UTC, chef-jojo commented on apps/web/next.config.mjs
> +        destination: '/info/pools',
Should invert?
old pools to pairs

2022-11-13 05:33 UTC, Woody810 commented on apps/web/next.config.mjs
> +        destination: '/info/pools',
let me check

2022-11-13 05:48 UTC, Woody810 commented on apps/web/next.config.mjs
> +        destination: '/info/pools',
fixed

2022-11-13 06:36 UTC, chef-jojo requested changes

2022-11-13 06:36 UTC, chef-jojo commented on apps/web/next.config.mjs
>          destination: '/info/pools/:address',
pairs

2022-11-13 06:36 UTC, chef-jojo commented on apps/web/next.config.mjs
> +      },
No need rewrites those

2022-11-13 06:43 UTC, Woody810 commented on apps/web/next.config.mjs
>          destination: '/info/pools/:address',
fixed

2022-11-13 06:44 UTC, Woody810 commented on apps/web/next.config.mjs
> +      },
fixed

2022-11-13 06:55 UTC, chef-jojo commented on apps/web/next.config.mjs
> +      },
remove

2022-11-13 06:55 UTC, chef-jojo commented on apps/web/next.config.mjs
>          destination: '/info/pools/:address',
nah should be pair -> pairs

2022-11-13 07:49 UTC, Woody810 commented on apps/web/next.config.mjs
> +      },
done

2022-11-16 05:23 UTC, chef-jojo approved these changes

2022-11-16 05:24 UTC, merged