feat: Make links in farm pair dropdown menu more descriptive
pancakeswap/pancake-frontend pull request #568
Opened 2021-03-03 20:30 UTC by memoyil

<img width="286" alt="Screenshot 2021-03-03 at 20 40 21" src="https://user-images.githubusercontent.com/2213635/109868287-bb40e480-7c67-11eb-8bf8-78c55d02feec.png">

2021-03-04 08:08 UTC, memoyil commented
@hachiojidev Could you please review this?

2021-03-05 16:13 UTC, memoyil commented
@Chef-Chungus  Could you please review this?

2021-03-08 01:25 UTC, Chef-Chungus approved these changes

2021-03-08 02:57 UTC, hachiojidev requested changes

2021-03-08 02:57 UTC, hachiojidev commented on src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
> +            Get {lpLabel}
Please add the translation to this

```
TranslateString(999, `Get ${lpLabel}`, { name: lpLabel })
```

2021-03-08 07:09 UTC, memoyil commented on src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
> +            Get {lpLabel}
done

2021-03-09 03:42 UTC, hachiojidev approved these changes

2021-03-09 03:42 UTC, merged