fix(aptos-Swap): Fix title placement
pancakeswap/pancake-frontend pull request #6076
Opened 2023-02-11 07:24 UTC by Woody810

Before:
![image](https://user-images.githubusercontent.com/109973128/218246146-d1ade91b-3806-4077-b025-1203998fd948.png)

After:
![image](https://user-images.githubusercontent.com/109973128/218246139-a6931c0f-227f-46bb-ab4c-ce010b6da02f.png)

2023-02-11 12:34 UTC, chefilip submitted a review, later dismissed

2023-02-11 16:02 UTC, chef-jojo requested changes
Please check not connected

2023-02-12 04:13 UTC, Woody810 commented
> Please check not connected

Fixed.

2023-02-13 05:59 UTC, chef-jojo approved these changes

2023-02-13 05:59 UTC, merged