feat(Swap): Add USDT in Common tokens
pancakeswap/pancake-frontend pull request #6209
Opened 2023-02-26 11:50 UTC by ChefMomota

2023-02-26 14:52 UTC, chef-jojo requested changes

2023-02-26 14:52 UTC, chef-jojo commented on apps/web/src/config/constants/exchange.ts
> +  [ChainId.BSC]: [bscTokens.usdt, bscTokens.cake, bscTokens.btcb],
Let's not remove busd

2023-02-27 07:12 UTC, ChefMomota commented on apps/web/src/config/constants/exchange.ts
> +  [ChainId.BSC]: [bscTokens.usdt, bscTokens.cake, bscTokens.btcb],
We need to remove BUSD

2023-03-02 06:35 UTC, chef-jojo approved these changes

2023-03-02 06:35 UTC, merged