feat(Swap): Show fetching best price
pancakeswap/pancake-frontend pull request #6532
Opened 2023-04-07 07:47 UTC by Woody810

https://user-images.githubusercontent.com/109973128/230566150-a63d25ce-b0c5-47eb-8caf-4d368021b28a.mov

2023-04-07 09:56 UTC, chef-jojo commented
showing previous value is a feature?

2023-04-07 10:08 UTC, Woody810 commented
> showing previous value is a feature?

The modification is to display "Fetching best price..." when loading prices, in order to alert users with slow internet connection.

2023-04-07 10:56 UTC, chefilip commented on packages/localization/src/config/translations.json
> +  "Fetching best pirce...": "Fetching best pirce..."
typo

2023-04-07 10:59 UTC, Woody810 commented on packages/localization/src/config/translations.json
> +  "Fetching best pirce...": "Fetching best pirce..."
Fiexd

2023-04-07 11:02 UTC, chef-jojo commented
I think the loading itself is presenting the loading
unless you add a onLoadingSlow flag if it's getting slow to get the result

2023-04-07 13:45 UTC, Woody810 commented
> I think the loading itself is presenting the loading unless you add a onLoadingSlow flag if it's getting slow to get the result

When loading exceeds 10 seconds, prompt the user "Fetching best price...".

2023-04-24 04:49 UTC, chef-jojo commented on apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
> +              {t('Searching For The Best Price')}
add Dots

2023-04-24 05:04 UTC, chef-jojo commented
I think we can hide the error when isLoading
https://github.com/pancakeswap/pancake-frontend/pull/6532/files#diff-d80ee63cb0033c8371bfe572adb8191b01ba0b78bfe7dd5e566f37ad334ba234R267

2023-04-24 05:10 UTC, Woody810 commented
> I think we can hide the error when isLoading https://github.com/pancakeswap/pancake-frontend/pull/6532/files#diff-d80ee63cb0033c8371bfe572adb8191b01ba0b78bfe7dd5e566f37ad334ba234R267

done

2023-04-24 05:27 UTC, chef-jojo requested changes

2023-04-24 05:27 UTC, chef-jojo commented on apps/web/src/views/Swap/V3Swap/containers/SwapCommitButton.tsx
> +              <Loading width="12px" height="12px" ml="4px" />
Let's remove the `Loading` and add Dots component instead of hardcoded
`<Dots>Searching For The Best Price</Dots>`

2023-04-25 04:04 UTC, chef-jojo approved these changes

2023-04-25 04:04 UTC, merged