fix: Wrong Until ticket sale progress when no wallet connected
pancakeswap/pancake-frontend pull request #781
Opened 2021-04-03 15:17 UTC by memoyil

Until ticket sale progress always shown and countdown from 1 hour till end of lottery draw when no wallet connected

2021-04-05 01:46 UTC, RabbitDoge requested changes
eslint warning

2021-04-05 05:34 UTC, memoyil commented
@RabbitDoge fixed

2021-04-05 06:22 UTC, hachiojidev approved these changes

2021-04-06 02:29 UTC, RabbitDoge approved these changes

2021-04-06 02:29 UTC, merged