fix: Fix dom key warning
pancakeswap/pancake-frontend pull request #832
Opened 2021-04-08 17:23 UTC by memoyil

`Warning: Received `true` for a non-boolean attribute `fill`. If you want to write it to the DOM, pass a string instead: fill="true" or fill={value.toString()}. h2 O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 LeadInBanner@http://localhost:3000/static/js/0.chunk.js:256:88 Home@http://localhost:3000/static/js/11.chunk.js:760:88 Route@http://localhost:3000/static/js/vendors~main.chunk.js:199424:29 Switch@http://localhost:3000/static/js/vendors~main.chunk.js:199626:29 Suspense SuspenseWithChunkError@http://localhost:3000/static/js/main.chunk.js:2201:5 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 Menu@http://localhost:3000/static/js/vendors~main.chunk.js:34938:17 Menu@http://localhost:3000/static/js/main.chunk.js:1432:76 Router@http://localhost:3000/static/js/vendors~main.chunk.js:199059:30 App@http://localhost:3000/static/js/main.chunk.js:86:58 ModalProvider@http://localhost:3000/static/js/vendors~main.chunk.js:33457:18 RefreshContextProvider@http://localhost:3000/static/js/main.chunk.js:9153:32 LanguageContextProvider@http://localhost:3000/static/js/main.chunk.js:8868:33 Ge@http://localhost:3000/static/js/vendors~main.chunk.js:214431:67 ThemeContextProvider@http://localhost:3000/static/js/main.chunk.js:9304:30 r@http://localhost:3000/static/js/vendors~main.chunk.js:195714:19 Provider@http://localhost:3000/static/js/vendors~main.chunk.js:196295:15 Web3ReactProvider@http://localhost:3000/static/js/vendors~main.chunk.js:39344:22 Providers@http://localhost:3000/static/js/main.chunk.js:454:19`

2021-04-08 23:39 UTC, hachiojidev requested changes

2021-04-08 23:39 UTC, hachiojidev commented on src/views/TradingCompetition/components/CompetitionHeadingText.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Please remove.

2021-04-08 23:39 UTC, hachiojidev commented on src/views/TradingCompetition/components/CompetitionHeadingText.tsx
> +import React from 'react'
Please put this at the top of the file.

2021-04-08 23:45 UTC, memoyil commented on src/views/TradingCompetition/components/CompetitionHeadingText.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Done

2021-04-08 23:45 UTC, memoyil commented on src/views/TradingCompetition/components/CompetitionHeadingText.tsx
> +import React from 'react'
Removed with new approach

2021-04-08 23:46 UTC, memoyil commented
@hachiojidev I changed the implementation and switch to transient props to not add them to dom

2021-04-09 14:17 UTC, ChefHutch reviewed
Nice. lgtm - warning no longer firing & visually the headings look fine. Will leave hachi to 👍  or 👎

2021-04-12 01:03 UTC, hachiojidev approved these changes

2021-04-12 01:03 UTC, merged