chore(foldable-text): Remove FoldableText from /TradingCompetition
pancakeswap/pancake-frontend pull request #852
Opened 2021-04-12 09:06 UTC by ChefHutch

- Remove component within views/TradingCompetition
- Update imports for FoldableText to use component within src/components

2021-04-12 09:13 UTC, hachiojidev requested changes

2021-04-12 09:13 UTC, hachiojidev commented on src/views/TradingCompetition/components/Rules/FAQs.tsx
> +import FoldableText from '../../../../components/FoldableText'
Absolute URL please.
```
... from "components/FoldableText"
```

2021-04-12 16:03 UTC, ChefHutch commented on src/views/TradingCompetition/components/Rules/FAQs.tsx
> +import FoldableText from '../../../../components/FoldableText'
Akh ofc, have updated.

2021-04-13 02:50 UTC, hachiojidev approved these changes

2021-04-13 02:50 UTC, merged