chore(trading-competition): Remove promotional LeadInBanner from page headers
pancakeswap/pancake-frontend pull request #889
Opened 2021-04-14 12:32 UTC by ChefHutch

Title says it all

2021-04-14 12:33 UTC, Chef-Chungus approved these changes

2021-04-14 12:33 UTC, ChefHutch commented on src/views/Home/Home.tsx
> -      <LeadInBanner />
Some fairly agressive diffs in here. In each instance the `<LeadInBanner>` is being removed as well as the wrapping fragment

2021-04-14 12:34 UTC, memoyil commented
LeadInBanner can stay, but we can empty it for future uses therefore we will not have to add it again in the future.

2021-04-15 10:43 UTC, RabbitDoge requested changes
If the component is not used anymore, please remove it

2021-04-16 01:10 UTC, RabbitDoge commented
#910

2021-04-16 01:10 UTC, closed without merging