chore: Remove deprecated jsx element
pancakeswap/pancake-frontend pull request #9029
Opened 2024-02-07 18:33 UTC by memoyil

---

## PR-Codex overview
This PR updates JSX.Element types to ReactNode in multiple files for better flexibility and compatibility with React components.

### Detailed summary
- Updated JSX.Element types to ReactNode in various interfaces and components for improved flexibility and compatibility with React components.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2024-02-08 02:04 UTC, chefjackson reviewed
How about we use ReactNode instead?

2024-02-08 09:45 UTC, chefjackson approved these changes

2024-02-08 09:46 UTC, chefjackson requested changes
seems having trouble with the build. Could you help check?

2024-02-15 05:35 UTC, ChefMomota approved these changes

2024-02-19 02:11 UTC, merged